import React from 'react'
 import { Link } from 'react-router-dom'
 import './Reflection.css';


 function Reflection() {
    return (
        <div>
            <div className='title'>Reflection</div>
            <div className='narrow'>
       <div className='What'>Coming into this project, it was important to keep an open mind and not let frustrations get to us. Our surrounding classroom environment all seemed to be in different places in the beginning with some finding immediate success and others debating whether or not they should switch user groups. We found ourselves to be in the middle of this range. I remember on the first day after getting our user groups, when I walked into Pete’s Pizza immediately becoming hypnotized by the aroma of the delicious mozzarella cheese cooking in the oven and although we left Pete’s without an interview scheduled, I was able to have a full belly which eased my nervousness of the future of our project. This was an example of one of our weaknesses during the project, not eating food but easily succumbing to laziness. It seemed like we had all the time in the world  to complete our project which opened a gate of idleness which now looking back at it, really slowed us down although we were able to bounce back shortly after proper planning in Figma and designating group roles. A specific cause of this laziness I believe stems from the World Cup. The peak of the World Cup began right in the middle of our project, killing our previous momentum of back to back interviews. Something had gone wrong in our planning and it was our responsibility as a group, to find the solution to this problem.
</div>
        <div className='SoWhat'>We have a flat tire in the middle of nowhere. It is time to evaluate what went wrong but more importantly, why it went wrong. After a really strong first 2 weeks heading into thanksgiving break, it felt really easy to just sit back and relax for a while. We let our guard down when we needed to maintain it the most, and with the World Cup starting, it was like beating a dead horse. This experience exposed a few flaws from my Designer mindset. For example, not keeping my Figma up-to-date after every engagement and being behind on making people portraits which are really important for gathering and organizing notes. For other/future designers/students in this class, this experience should serve as an example that no matter how ahead you might be at a certain point in your journey, never get too comfortable and don’t be consumed by outside distractions no matter how tempting, focus on the task at hand. This is important because there will be a lot of distractions throughout your journey whether it be school related or not. Make sure you and your team are all on the same page both schedule-wise and emotionally; team health is very important and can either MAKE or BREAK your journey. 
</div>
        <div className='NowWhat'>The worst thing you can do with a flat tire is to complain and bathe in your sorrows about how horrible your current situation is. You should instead focus on your next steps and how you will combat this failure. I believe that was our biggest strength as a group; being able to fight against our bad habits. If you are facing a rough patch you shouldn't think about what went wrong for too long, time is valuable. Check in with your team, you might need to rework your plan; for example, instead of sending barrages of emails to bigger food chains, we decided to go in person to smaller cafe’s because we know there is more community value in a small cafe than there is at a Wendy's. Once you have inflated your tire, it’s time to start thinking about the road ahead, the final destination, the bigger picture. Your end goal of this entire project is to ultimately create a project that overall benefits your user group and you can’t do that without learning the themes and having insights of your user group. After finishing all your engagements, it’s time to look over your figma and make sure everything is up to date. You want to paint a picture that shows your connections rather than telling a story that talks about youth connections. There are several limitations to lessons that can make them less portable to other designers working in different contexts with different stakeholders. There are contextual factors which are  lessons that are effective in one context may not be as effective in another context due to differences in values, expectations, and other contextual factors. For example, a lesson that is effective in a classroom setting may not be as effective in a workplace setting due to the different expectations and needs of the learners. Another example would be the specificity of a lesson. Lessons that are too specific or focused on a particular task or skill may not be as portable to other contexts. 
</div>
        <div className='LooksLike'>Throughout this reflection, I compare this project to a road trip that has gone wrong for 3 reasons. 1. The road trip and the design process are both two very long journeys. The work can seem never ending at times whether it be staying awake behind the wheel or staying awake creating personas on Figma, both journeys can be extremely tiring but can be helped by next connection, 2. You need great roadmates and team members. In order to have an enjoyable trip, you need good roadmates to keep you company. You need to keep energy high so the group can feed off of each other. Like your design team, you need to all be on the same page if you want to get work done. You need schedules and deadlines or else you won’t move forward. 3. You will encounter failure. Whether it be a flat tire or empty gas tank, you will encounter failure on your road trip just like how a moment of failure is inevitable for your design group but remember, the problem isn't “how bad will this slow us down?”, but rather, “how quickly can we rebuild?”.
</div>
        </div>
       </div>
   )
}



export default Reflection;
